apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: network-controller-server-unix
  namespace: default
spec:
  selector:
    matchLabels:
      name: network-controller-server-unix
  template:
    metadata:
      labels:
        name: network-controller-server-unix
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: network-controller-server-unix
        image: sdnvortex/network-controller:latest
        securityContext:
          privileged: true
        command: ["/go/bin/server"]
        args: ["-unix=/tmp/vortex.sock", "-netlink-gc"]
        volumeMounts:
        - mountPath: /var/run:shared
          name: docker-sock
          #          mountPropagation: Bidirectional
        - mountPath: /tmp/
          name: grpc-sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /run
      - name: grpc-sock
        hostPath:
          path: /tmp/vortex
      hostNetwork: true
