language: go
sudo: true
go: 
     - 1.9.x

notifications:
    email:
        recipients: 
            - hwchiu@linkernetworks.com
            - cwlin@linkernetworks.com
        on_success: change
before_install:
    - sudo apt-get install -y git build-essential openvswitch-switch
    - go get -u github.com/kardianos/govendor
    - go get -u github.com/pierrre/gotestcover
    - make pb
install: 
    - govendor sync
script:
    - sudo -E env PATH=$PATH gotestcover -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
    - bash <(curl -s https://codecov.io/bash)
